version: '3.9'
services:
  weather-app:
    image: app/weather-app
    container_name: weather-app
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    environment:
      - WEATHER_API_KEY=H89GMLXWHQN7VAP44ZP2YF4KM