version: '3.9'
services:
  orderbox:
    image: app/flaskblog
    container_name: flaskblog
    build: 
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app